---

- name: Sample VM build
  hosts: localhost
  gather_facts: false
  roles:
    - packages
    - networks
    - cloud-image

- name: VMs
  hosts: all
  gather_facts: false
  roles:
    - build-os
    - build-disks
    - cloud-init
    - build-vms
    - build-inv
